
CXX = g++

LIBS = -lglut -lGLU -lGL
PROGRAM = main
OUTPUT = project1
#_1D
#Kilde


$(PROGRAM): $(PROGRAM).cpp 
		$(CXX) $(PROGRAM).cpp -o $(OUTPUT) $(LIBS)
#nrutil.c 
#nrutil.h nrutil.c
clean: 
		rm -f *.o